language: cpp
dist: xenial
sudo: false

addons:
    apt:
        packages:
        - tclsh
        - pkg-config
        - cmake
        - libssl-dev
        - build-essential
    homebrew:
        packages:
        - openssl

matrix:
    include:
        - env: BUILD_TYPE=Debug
        - env:
          - BUILD_TYPE=Debug
          - BUILD_OPTS=-DENABLE_LOGGING=OFF
        - env: BUILD_TYPE=Release
        - os: osx
          osx_image: xcode10.2
          env: BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode10.2
          env: BUILD_TYPE=Release
        - os: linux
          compiler: x86_64-w64-mingw32-g++
          addons:
            apt:
              packages:
                - gcc-mingw-w64-base
                - binutils-mingw-w64-x86-64
                - gcc-mingw-w64-x86-64
                - gcc-mingw-w64
                - g++-mingw-w64-x86-64
          before_script:
            - git clone -b OpenSSL_1_1_1-stable https://github.com/openssl/openssl.git openssl
            - cd openssl
            - ./Configure --cross-compile-prefix=x86_64-w64-mingw32- mingw64
            - make
            - cd ..
          env: BUILD_TYPE=Release
        - name: Static checks (clang-format)
          env: STATIC_CHECKS=yes
          os: linux
          compiler: gcc
          addons:
            apt:
              sources:
                - llvm-toolchain-xenial-8
              packages:
                - clang-format-8

script:
    - if [ "$STATIC_CHECKS" == "yes" ]; then
        find ./srtcore/ -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \) -print0 | xargs -r0 clang-format -i;
        git diff --color --exit-code;
      elif [ "$TRAVIS_COMPILER" == "x86_64-w64-mingw32-g++" ]; then
        export CC="x86_64-w64-mingw32-gcc";
        export CXX="x86_64-w64-mingw32-g++";
        cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE $BUILD_OPTS -DENABLE_UNITTESTS="ON" -DUSE_OPENSSL_PC="OFF" -DOPENSSL_ROOT_DIR="$PWD/openssl" -DCMAKE_SYSTEM_NAME="Windows";
      elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
        cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE $BUILD_OPTS -DENABLE_UNITTESTS="ON";
      elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
        export PKG_CONFIG_PATH=$(brew --prefix openssl)"/lib/pkgconfig";
        cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE $BUILD_OPTS -DENABLE_UNITTESTS="ON";
      fi
    - if [ "$STATIC_CHECKS" != "yes" ]; then make; fi
    - if [ "$STATIC_CHECKS" != "yes" AND "$TRAVIS_COMPILER" != "x86_64-w64-mingw32-g++" ]; then
        ctest --extra-verbose;
      fi
